# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality checks (Node ${{ matrix.node }})
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        node: [22.x]
    env:
      NODE_ENV: test
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: |
          if [ -f node_modules/.bin/eslint ]; then
            npm run lint
          else
            echo "Skipping lint: eslint not installed."
          fi
      - name: Compile TypeScript
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: ignore

  docker:
    name: Build Docker image
    runs-on: self-hosted
    needs: quality
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build --file Dockerfile --tag opo-backend:${{ github.sha }} .
      - name: Smoke test image
        run: docker run --rm --entrypoint node opo-backend:${{ github.sha }} --version
      - name: Run container on port 8000
        run: |
          docker run -d --name opo-backend-${{ github.sha }} -p 8000:8000 opo-backend:${{ github.sha }}
          docker ps --filter "name=opo-backend-${{ github.sha }}"
      - name: Show container logs
        if: always()
        run: docker logs opo-backend-${{ github.sha }} || true
      - name: Stop container
        if: always()
        run: |
          docker stop opo-backend-${{ github.sha }} || true
          docker rm opo-backend-${{ github.sha }} || true
